repos:
# https://github.com/renovatebot/helm-charts
- name: renovate
  url: https://docs.renovatebot.com/helm-charts

charts:
- name: renovate/renovate@23.73.2
- name: arhat-dev/renovate-server@0.1.3
