environments:
# a cluster in clusters/sample-foo
- name: sample-foo
  kubeContext: sample-bar
  deployments:
  - name: testing/redis
    chart: bitnami/redis@11.1.0
    baseValues: values-production.yaml

# another cluster in clusters/sample-bar
- name: sample-bar
  kubeContext: sample-bar
  deployments:
  - name: monitoring/promop
    chart: prometheus-community/kube-prometheus-stack@10.0.1
    # namespaceInTemplate: true
    # baseValues: values.yaml
  - name: storage/postgresop
    chart: zalando/postgres-operator@v1.5.0
    baseValues: values-crd.yaml
