repos:
# https://github.com/jupyterhub/helm-chart
- name: jupyterhub
  url: https://jupyterhub.github.io/helm-chart

charts:
- name: jupyterhub/jupyterhub@0.10.2
- name: jupyterhub/binderhub@0.2.0-n361.h6f57706
