repos:
# https://github.com/influxdata/helm-charts
- name: influxdata
  url: https://helm.influxdata.com

charts:
- name: influxdata/influxdb@4.8.10
- name: influxdata/influxdb2@1.0.13
- name: influxdata/influxdb-enterprise@0.1.12
- name: influxdata/chronograf@1.1.23
- name: influxdata/kapacitor@1.3.1
- name: influxdata/telegraf@1.7.34
- name: influxdata/telegraf-ds@1.0.19
- name: influxdata/telegraf-operator@1.1.5

- name: bitnami/influxdb@2.0.0
