name: CI

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Lint
      run: |
        make lint.all

    - name: Validation
      run: |
        make check.all

    # TODO: remove this test case once you have created a new repo from this repo
    - name: Test sample cluster
      run: |
        sh scripts/helm-stack.sh -c .helm-stack -c docs/sample-cluster ensure
        sh scripts/helm-stack.sh -c .helm-stack -c docs/sample-cluster gen all
